# @File    : englishwords.py
lis = ['', 'settle', 'oppose', 'mood', 'craftsman', 'agitate', 'catholic', 'go-ahe', 'bribery', 'emphasize',
       'reference', 'directory', 'philosopher', 'indirectly', 'defendant', 'arrange', 'undertreatment', 'intimate',
       'suspicion', 'hostage', 'random', 'differentiate', 'nervous', 'disputable', 'expectation', 'declare', 'rearing',
       'burst', 'tag', 'milestone', 'tricky', 'inflation', 'revolve', 'materialism', 'term', 'strain',
       'take charge of= be in charge of', 'stationary', 'directive', 'renounce', 'side with', 'wonder', 'talent',
       'conduct', 'analogy', 'distract', 'remains', 'drawback', 'fondness', 'resolve', 'blot', 'inferiority',
       'headhunter', 'immigration', 'mathematical', 'resemblance', 'bash', 'headache', 'notice', 'dormant', 'fierce',
       'alternative', 'code', 'illustrate', 'organize', 'admit', 'sensational', 'weight', 'be proficient in',
       'contemporary', 'colony', 'relief', 'counter', 'excessive', 'prosperous', 'level', 'partial', 'transform',
       'get cracking', 'hydrogen', 'introductory', 'refreshment', 'unemployment rate', 'elderly', 'subjective', 'image',
       'notify', 'incompetent to do sth', 'mildly', 'scapegoat', 'formula', 'nominate', 'abreast of', 'suspension',
       'incompetent', 'eliminate', 'mobile', 'schedule', 'meet the expectation', 'require', 'routine', 'agreement',
       'provided', 'anticipate', 'enhanced', 'observe', 'scale', 'massacre /', 'respond', 'collapse /', 'grant',
       'peculiarity', 'self-governing', 'congress', 'constrain', 'be characterized by', 'prudent', 'vastly',
       'complicate', 'inject into', 'abandon', 'underfund', 'immune', 'chief', 'imaginative', 'entail', 'crown',
       'inhabit', 'review', 'product', 'decisive', 'specify', 'imaging', 'wine', 'intentionally', 'knit', 'press',
       'dramatic', 'hedge', 'skeptical', 'dramatize', 'attorney', 'in response to', 'textile', 'motto', 'autonomous',
       'overstate', 'inquiry', 'auto', 'medieval', 'institutional', 'dim', 'emerge from', 'site', 'irrigation',
       'persist', 'retreat from', 'depress', 'traffic jam', 'nowhere', 'addict', 'disorder', 'establish', 'lenient',
       'remark', 'bulb', 'symposium', 'stockholder', 'sector', 'moral code', 'consist in /of', 'virtuosity', 'function',
       'reign', 'sufficient', 'suspend', 'understatement', 'illegal', 'genetic', 'picture', 'commune',
       'prejudice against', 'esteem', 'misinterpret', 'admission', 'well-balanced', 'capacity', 'dealing', 'repent of',
       'surface', 'precise', 'expel', 'immediately', 'joint', 'stereotype', 'spontaneous', 'amend', 'outline', 'worth',
       'muscular', 'novel', 'depressant', 'satellite', 'moderate', 'market', 'disappear', 'sustain', 'baseline',
       'dispute', 'grief', 'contradictory', 'indicate', 'advertisement', 'distinct', 'worldview', 'conform', 'stable',
       'conductor', 'circuit   integrate', 'initial', 'necessity', 'lest', 'arbitrary', 'approve', 'farther', 'effort',
       'on view', 'inevitable', 'crack', 'favorite', 'alleviate', 'tell', 'optional', 'trial', 'returning',
       'uniformity', 'identify', 'print', 'oppress', 'predominantly', 'defender', 'conformity', 'pause',
       'integrate with', 'primarily', 'pledge', 'primitive', 'faraway', 'in practice', 'rush through', 'concern',
       'specialize in', 'orbital', 'toxic', 'primary', 'qualify', 'geologist', 'considering prep.',
       'beyond one’s comprehension', 'coastline', 'electronic', 'issue', 'identify with', 'arouse', 'allege',
       'be fond of', 'at fault', 'attendant', 'survey', 'tragedy', 'component', 'pink slip', 'hold up', 'explicit',
       'discipline', 'commercialized', 'positive', 'impose sth. on', 'mere', 'headway', 'intricate', 'manifestation',
       'for instance', 'be dissatisfied with', 'obsession', 'favorable', 'blueprint', 'nasty', 'conclusive', 'respect',
       'penalty', 'state', 'adopt', 'at the top ofone’slungs', 'forecast', 'radical', 'flourish', 'article', 'agenda',
       'brand', 'emergence', 'IMF      I n t e r na t i o n a l Monetary Fund', 'no wonder', 'distinguished',
       'textile industry', 'suffering', 'overseas', 'organizational', 'element', 'latter', 'statistic', 'rally',
       'disperse', 'dissatisfied', 'switch off', 'plot', 'rule out', 'fulfill', 'pension', 'grace', 'bunch',
       'appropriate', 'deduce', 'swing', 'matter', 'strive for', 'suspicious', 'hold out', 'inflate', 'correlate',
       'parallel', 'unrecognized', 'outsize', 'deteriorate', 'vote', 'be reluctant to do sth', 'surrender',
       'discontent', 'indeed', 'capable', 'Spanish', 'feeble', 'reasoned', 'intellectual property', 'criticize',
       'sweep', 'boast', 'incorporate with', 'be compelled to', 'frontier', 'permit', 'withdraw', 'panorama',
       'industrialized', 'damn excalm.', 'compress', 'leup to', 'artificial', 'hardship', 'deprive', 'a bunch of',
       'responsible', 'switch', 'comparative', 'civil', 'access to', 'equally', 'preach', 'circulate', 'lengthen',
       'religion', 'courteous', 'glare at', 'enthusiasm', 'dullness', 'psychology', 'allow for', 'be exposed to',
       'election campaign', 'crime', 'retailer', 'mistrusted', 'ultimately', 'reasonable', 'lever', 'commit',
       'incompetently', 'mankind', 'remote', 'pour into', 'immune … to', 'resistance', 'characterize', 'prominent',
       'motivate', 'acknowledge', 'insistence', 'cape', 'slum', 'subtle', 'government', 'recovery', 'poet',
       'in return for', 'sort sth. out', 'be an item 〈〉', 'subtitle', 'defect', 'collective', 'knowledgeable',
       'military', 'neglect', 'electronics', 'geological', 'likewise', 'dispose of', 'employer', 'certainly',
       'combine with', 'intent', 'virtual', 'provider', 'FBI       F e d e r a l  B u r e a u  o f Investigation',
       'dissatisfaction', 'physical', 'reasonably', 'manager', 'and so forth', 'universally', 'necessary', 'sheer',
       'career', 'question', 'succeed', 'be opposed to', 'electronically', 'initiate', 'procreation', 'overwhelm',
       'pathological', 'structure', 'adapt', 'marked', 'originate', 'assemble', 'rival', 'internal',
       'no to mention doing sth.', 'hemisphere', 'rare', 'trust', 'substantial a d', 'reduce', 'ingrain', 'access',
       'executive', 'encounter', 'inspire', 'counseling', 'accelerating', 'peak', 'paradoxical', 'extend', 'imitation',
       'mark', 'conjunction', 'copyright', 'drop out', 'effective', 'in line with', 'concede sth. to sb.', 'dwell',
       'corporation', 'do one’s level best', 'global', 'gain', 'owing to', 'devalued', 'distrust', 'provision',
       'prophet', 'meaning', 'capture', 'principal', 'infrequently', 'hook', 'legislation', 'damage', 'with respect to',
       'subconscious', 'spot', 'economic', 'coverage', 'shelter', 'repertoire', 'extensive', 'plefor', 'banquet',
       'concluding', 'triumph', 'varying', 'proclaim', 'publicized', 'impulse', 'insist', 'instant', 'poverty',
       'demonstrate', 'equal', 'heighten', 'reflection', 'panel', 'conductive', 'incapable', 'financial',
       'environmental', 'in view', 'vigorously', 'row', 'payment', 'irritate', 'occupy', 'presence', 'brittle',
       'outlive', 'rear', 'plain', 'unquestioned', 'decline /', 'section', 'blackened', 'indefinitely', 'essence',
       'forerunner', 'assert', 'lay claim to', 'unfamiliar', 'core', 'casualty', 'accelerate', 'federal', 'subsidy',
       'puzzlement', 'inaccuracy', 'retreat', 'poisonous', 'unparalleled', 'democratize', 'increased', 'level off',
       'modify', 'comparable', 'enlighten', 'law', 'prove', 'perplex', 'overvalue', 'formulate', 'engage', 'revive',
       'enormous', 'orient', 'earnest', 'poetry', 'humble', 'probe', 'coherent', 'undermine', 'discomfort', 'at large',
       'previous', 'marketer', 'represent', 'tone', 'occurrence', 'otherwise', 'imitate', 'confer', 'bulky', 'private',
       'numerical', 'infection', 'impress', 'counterbalance', 'be entitled to', 'episode', 'establish oneself in',
       'celebrity', 'divide', 'get close to', 'concession', 'satisfy', 'the Lower House/the Lower Chamber', 'stuff',
       'lobbying', 'irrespectively', 'ratio', 'persevere', 'mainland', 'horizon', 'accountant', 'profitable', 'overall',
       'CIA    Central Intelligenc e Agency', 'practically', 'bind', 'a great deal of', 'impose', 'evidence', 'lobby',
       'wing', 'farcical', 'form', 'spur', 'remind', 'hold', 'anticipate sb. doing sth.', 'verify', 'fearful',
       'to some extent', 'asset', 'trivial', 'denote', 'geology', 'inform', 'mutually', 'stumble across', 'official',
       'holder', 'merit', 'explanation', 'layer', 'sanction', 'in public', 'lawful', 'privilege', 'fade', 'instrument',
       'discover', 'intelligence', 'statistical', 'float', 'incident', 'legal', 'on account of', 'repel', 'commercial',
       'conspiracy', 'definite', 'catch/get a glimpse of', 'recipient', 'stripe', 'suppress', 'glow', 'curb',
       'flexible schedule', 'coordinate', 'heir', 'clothe', 'extract', 'simply', 'statement', 'cater to', 'attendance',
       'pro', 'nonsense', 'deliver', 'durable', 'glide', 'gold rush', 'poisoning', 'well-meaning', 'value', 'public',
       'circular bus route', 'commy', 'recognize', 'alternatively', 'logical', 'mutual benefit', 'miss', 'distinguish',
       'route', 'uncommon', 'hamper', 'exclude', 'administer', 'alliance', 'estimate', 'acquaint', 'credible', 'mode',
       'puzzle', 'remarkable', 'extreme', 'elaborate', 'incline', 'brainstorm', 'inferior', 'plateau', 'upheaval',
       'segment', 'glimpse', 'color', 'performative', 'specialize', 'bearing', 'invention', 'astrophysicist',
       'assessment', 'online', 'accuracy', 'prolong', 'intelligent', 'geophysical', 'exhaust', 'gape', 'in a rage',
       'define', 'stretch', 'pose', 'figure out', 'transfer', 'interview', 'deplorable', 'convention', 'earnestness',
       'recover', 'resident', 'distribution', 'permanent', 'dominate', 'pharmaceutical', 'announce', 'scary', 'rarely',
       'in respond to', 'publicity', 'triviality', 'repeatedly', 'significant', 'military intelligence',
       'intend to do/intend doing sth.', 'portray', 'enforce', 'meet', 'headlong',
       'under the circumstances = in the circumstances  threaten   prospect', 'highlight', 'item', 'industry',
       'shortcoming', 'rejection', 'doubtful', 'engagement', 'rational', 'alcohol', 'viewer', 'harmful', 'bureaucrat',
       'current', 'pressing', 'underlie', 'blast', 'sentiment', 'behavior', 'informally', 'keep abreast of', 'virus',
       'preferable', 'quote', 'upset', 'reason', 'marine', 'leave sth. out of account', 'effectiveness', 'auditor',
       'furthermore', 'dull', 'court', 'occasionally', 'breadth', 'fund', 'largely', 'fragile', 'zigzag', 'aroma',
       'occupation', 'ensure', 'biomass', 'organic', 'rustle', 'creationism', 'split', 'foremost', 'cultivation',
       'return', 'remaining', 'incur', 'being', 'imaginary', 'as/so far as ... be concerned', 'entitle', 'contend',
       'ordinary', 'proverb', 'shareholder', 'descend', 'Greek', 'personnel', 'extended', 'clothes', 'expectancy',
       'be subject to', 'outpouring', 'punishment', 'later', 'sake', 'promising', 'underline', 'charter', 'hypothesis',
       'hitherto', 'ingredient', 'unchallenged', 'otherwise ad', 'variety', 'be succeeded by', 'press for',
       'take the le', 'ambiguous adj', 'equate', 'partner', 'fiscal cliff', 'by means of', 'confer sth. on sb.',
       'ballot', 'orbit', 'obtainable', 'highly', 'refreshing a d', 'hospitality', 'stain', 'feature', 'aggravate',
       'gravity', 'colonial', 'emergency', 'headline', 'manageable', 'deliberate', 'unimaginable', 'senate',
       'be acquainted with', 'dividend', 'manage', 'cope with', 'knowledge', 'available', 'impinge', 'lie',
       'productive', 'elsewhere', 'transaction', 'certify', 'diffuse', 'pursue', 'unenlightened', 'endure',
       'for the sake of', 'conception', 'formation', 'precisely', 'immigrant', 'infect', 'desert', 'devastating',
       'steward', 'surroundings', 'disturbance', 'exaggerate', 'substance abuse', 'reformatory', 'norm', 'ancestral',
       'turbulent', 'justify', 'delivery', 'merely', 'predicament', 'abuse one’s authority', 'music therapy', 'comedy',
       'worth doing sth.', 'prohibit', 'eligible', 'corresponding', 'reader', 'determine', 'assure', 'ple', 'prior',
       'systematically', 'outcome', 'expect', 'slip', 'request', 'shift', 'access ro', 'sink', 'low-level', 'reviewer',
       'transferable', 'definition', 'intrusion', 'let alone', 'contest', 'address', 'enhancement', 'hinder',
       'liveliness', 'supplier', 'sympathy', 'be bound to', 'quantity', 'discrimination', 'yield to', 'uphold', 'weigh',
       'view', 'counterpart', 'bear', 'trait', 'formal', 'virtually', 'marketplace', 'taxation', 'bewilder', 'outrage',
       'familiar', 'harsh', 'hardline', 'bodily', 'release', 'resentment', 'menace', 'constitute', 'suspiciously',
       'substantiate', 'arbiter', 'consideration', 'celebrate', 'afford', 'bureaucracy', 'part and parcel',
       'lesomeone on', 'Pearl Harbor', 'leading', 'false', 'susceptible', 'individually', 'possess', 'happen', 'symbol',
       'strive', 'appear', 'stumble upon', 'variation', 'be available to', 'in respect of', 'violent', 'guideline',
       'at/on short notice', 'the House of Lordsof Britain/the Upper House', 'densely', 'comparatively', 'instantly',
       'therapy', 'household', 'fraction', 'entertainment', 'participate in', 'retain', 'various', 'lawyer', 'creative',
       'conclude', 'shield', 'native', 'hypocritical', 'variable', 'vague', ' restrain sb from doing sth', 'grain',
       'stimulate', 'wise', 'loading procedure', 'resume', 'efficient', 'intranet', 'notion', 'toddler', 'climax',
       'fragment', 'take notice of ：', 'authentic', 'wisely', 'participate', 'enterprise', 'annoy', 'vocabulary',
       'in favor of', 'mold', 'deputy', 'acquaintance', 'reinforce', 'collaboratively', 'supposedly', 'phase',
       'compromise', 'parcel', 'suffer sth./suffer from sth', 'show', 'estate', 'be hostile to', 'excel in /at',
       'confirmation', 'conceive', 'junction', 'practicality', 'supply', 'inherent', 'artistic', 'doubter', 'crisis',
       'inclusive', 'be composed of', 'simple', 'bursting', 'descendant', 'strategy', 'confer with', 'hefor',
       'refrain from doing sth /', 'conscious', 'depart', 'span', 'opportion', 'parachute', 'industrialization', 'line',
       'expose', 'undistracted', 'directly', 'misinterpretation', 'identity', 'integrated', 'fond', 'tedious',
       'emigrate', 'chancellor', 'cater for', 'indispensable', 'bond', 'religious', 'version', 'critic', 'republican',
       'assault on sb', 'universal', 'coordinated', 'observer', 'fashionable', 'reluctantly', 'regrettable', 'blunder',
       'series', 'practitioner', 'affluent', 'courageous', 'cater', 'extent', 'laboratory', 'statute', 'incidence',
       'instance', 'afford to', 'accelerated', 'odd', 'strengthen', 'flaw', 'terminally', 'complexity', 'ineffective',
       'publish', 'cooperate', 'unacceptable', 'pole', 'contempt', 'switch on', 'domestic', 'perceive', 'doctrine',
       'disclose', 'confirm sb. in', 'express', 'exhausted', 'content', 'acclaim', 'slacken', 'competently',
       'expansion', 'expenditure', 'essential', 'Internet-based', 'distribute', 'anticipation', 'guaranteed', 'network',
       'organism', 'decorate', 'deal with', 'temporary', 'unambiguous', 'faint', 'decline', 'encourage', 'land',
       'laughing stock', 'pour', 'accidentally', 'resign', 'governance', 'reliant', 'practice', 'significance',
       'committee', 'gaze at', 'metropolitan a d j .', 'interpretation', 'printout', 'contribute', 'be neglectful of',
       'chop', 'aggregation', 'environmentally', 'manipulation', 'virtue', 'lawsuit', 'burst into', 'key', 'structural',
       'solve', 'faulty', 'disaster', 'amendment', 'intellect', 'profoundly', 'ecosystem', 'inference', 'length',
       'baby boom', 'set forth', 'airline', 'frequently', 'intellectualism', 'renaissance', 'monopoly',
       'be governed by', 'revise', 'evolve', 'crucial', 'take sth. in view = take sth. into account', 'negative',
       'lure', 'pioneer', 'outbreak', 'consuming', 'lapse', 'context', 'speculate', 'pronouncement', 'progressive',
       'incidental', 'environment', 'Hispanic', 'whereas', 'biological', 'outlook', 'note', 'reminder /', 'dose',
       'organization', 'sample', 'indefinite', 'former', 'conclusion', 'material', 'goods', 'commit oneself to',
       'atmosphere', 'property', 'suitable', 'legitimate', 'detail', 'satisfied', 'reap', 'take/make notes', 'agency',
       'stock', 'suppose', 'emphasis', 'obscure', 'hijack', 'readily', 'dwarf', 'option', 'gratitude', 'compensation',
       'intend', 'admonish', 'facilitate', 'vary', 'environmentalist', 'overriding', 'digest', 'entitlement', 'opaque',
       'conserve energy', 'priority', 'cracked', 'well-established', 'original', 'be curious about/to', 'socioeconomic',
       'informative', 'gentle', 'escape /', 'in sympathy with', 'initiative', 'designate', 'table',
       'make a concession/some concessions to', 'masterpiece', 'be good at', 'put trust in sb./sth', 'sensation',
       'be satisfied with', 'succession', 'perpetual', 'invalid', 'affirm', 'diversion', 'modification',
       'as a matter of fact', 'objective', 'claim', 'contemptible', 'relieve', 'courage', 'tactic', 'in no doubt',
       'substantially', 'shallow', 'backward', 'feudalism', 'stimulation', 'lung', 'approximately', 'inset', 'brain[pl',
       'merge', 'spouse', 'demolition', 'aspire to', 'institute', 'unconscious', 'yield', 'prey', 'chronological',
       'concept', 'cover', 'proportion', 'firm', 'undertake', 'rebound', 'poor', 'relate', 'lean', 'offer', 'summit',
       'rage', 'temperament', 'leto', 'let out', 'get rid of', 'patent', 'distant', 'external', 'renew', 'recreate',
       'disposition', 'systematic', 'individual', 'steady', 'excellent', 'measure', 'shareholding', 'independent',
       'privacy', 'cling', 'potential', 'ineffectual', 'finally', 'entrepreneur', 'though', 'forth', 'armed',
       'endurance', 'compare to', 'moreover', 'operational', 'unavoidable', 'poorly', 'cell', 'puzzled',
       'misinformation', 'starting procedure', 'classify', 'reject', 'anonymous', 'halt', 'correspondent', 'impel',
       'commitment', 'antigravity', 'fiasco   vain   abuse', 'remold', 'superficial', 'install', 'flavor',
       'alphabetically', 'critical', 'guarantee', 'reduction', 'create', 'apprise', 'patrol', 'means', 'curve',
       'creature', 'substitute … for …', 'pessimistic', 'betray', 'disorganized', 'on the level', 'demerit',
       'panel discussion', 'inflame', 'devastate', 'terminal', 'arise', 'possession', 'master', 'provide', 'dependent',
       'lineage', 'nonconformist', 'stumble', 'predominance', 'confirm', 'govern', 'objectivity', 'render', 'objection',
       'molecule', 'radically', 'miserable', 'accurate', 'disclaim', 'historian', 'errand', 'competitive', 'decrease',
       'extremely', 'foundation', 'compete against/with', 'commerce', 'forsake', 'intention', 'enlarge', 'immediate',
       'resort', 'posture', 'paramount', 'agent', 'disgrace', 'brake', 'maladapted', 'threat', 'similarity', 'purpose',
       'retail', 'inconclusive', 'landing', 'expression', 'conservative', 'employee', 'epidemic', 'be adept at',
       'divided', 'congregate', 'imagine', 'deny', 'bruise', 'huge', 'enhance', 'revolutionary', 'integration',
       'sketch', 'wonderful', 'dentist', 'elitism', 'theological', 'factor', 'petrol', 'divorce', 'increasingly',
       'professionalization', 'compare with', 'affiliation', 'prevent', 'situation', 'possible', 'regulate', 'refuse',
       'in the presence of', 'catastrophe', 'establishment', 'in spite of', 'impressive', 'personality', 'printer',
       'extravagant', 'dreadful', 'take ... for granted', 'generate', 'unexpected', 'noteworthy', 'compare',
       'back-and-forth', 'come up to', 'compensate for', 'weary', 'drop by', 'compete', 'cite', 'drought', 'defend',
       'side', 'control', 'disposable chopsticks', 'relate to', 'in print', 'evaluation', 'utmost', 'harbor',
       'in terms of', 'trust fund', 'mock', 'assess', 'late', 'reluctant', 'treat', 'profound', 'misle', 'stakeholder',
       'leader', 'astrological', 'dumb', 'status', 'prosperity', 'balance', 'hold on 〈〉', 'landmark', 'personal', 'owe',
       'explicitly', 'lack', 'despite prep.', 'commissioner', 'bin', 'boundary', 'involvement', 'scattered',
       'criticism', 'biased', 'contract', 'restructuring', 'competent', 'overturn', '[', 'controversy', 'locate',
       'convey', 'requirement', 'predict', 'ecologically', 'he', 'attribute', 'have some bearing on',
       'the State Council', 'comprehensive', 'fundamentally', 'consciousness', 'exceptional', 'creation', 'work',
       'fury', 'evade', 'prompt', 'audience', 'restore', 'functional', 'consider', 'hurdle', 'as opposed to',
       'bellyful', 'economically', 'slack', 'ghost', 'subsequent', 'literally', 'alive', 'tumble', 'launch', 'mutual',
       'devil', 'charitable', 'bias', 'desirable', 'conservation', 'connection', 'live', 'negotiate', 'composition',
       'encode', 'bother', 'prevail', '5', 'meaningless', 'system', 'give up', 'interrelated', 'frustrate', 'position',
       'concern oneself with', 'equality', 'institution', 'approach', 'temper', 'working procedure', 'testify',
       'plausible', 'discourage', 'statesman', 'reflect', 'escalate', 'correlated', 'numerous', 'be qualified for',
       'livelihood', 'mathematics', 'considerable', 'administrate', 'emotion', 'be frustrated by/with', 'glitter',
       'deal', 'bold', 'scheme', 'lie in', 'cultivate', 'sign', 'empower', 'accompany', 'bother to do', 'lie with sb.',
       'plump', 'large', 'passion', 'contact', 'respectable', 'uncover', 'be familiar with', 'withhold', 'eve',
       'democracy', 'the South Pole', 'jam', 'bypass', 'separate', 'equivalent', 'cast off', 'flagstone', 'survive',
       'outlay', 'unconcerned', 'expense', 'frankly', 'parliamentary', 'alarmist', 'counsel', 'circumstance', 'net',
       'self-contradictory', 'professionalize', 'forecaster', 'randomly', 'central', 'dissolve', 'quantitative',
       'microscope', 'opposition', 'elevate', 'elite', 'commodity', 'obstacle', 'be supposed to', 'indulge',
       'emissions-free', 'fume', 'adornment', 'peer', 'archaic', 'simulation', 'figure', 'prompting', 'nostalgia',
       'effect', 'incorporate', 'vigorous', 'array', 'humankind', 'printing', 'desire', 'beam', 'costly', 'debate',
       'manufacturer', 'evident', 'artificial intelligence', 'stare at', 'uninformed', 'e-commerce', 'impact',
       'unimpressive', 'clarity', 'production', 'shrink', 'devoted', 'elimination', 'myth', 'morality', 'implication',
       'proposition', 'unreflecting', 'respectively', 'formidable', 'endorse', 'recast', 'performance', 'readmit',
       'ultimate', 'glowing', 'steer', 'agitated', 'entertaining', 'contention', 'invest', 'perspective', 'misery',
       'creationist', 'deadline', 'in consequence', 'stock market', 'emerge', 'manufacturing', 'complex', 'deductible',
       'varied', 'corporate', 'synthetic   articulately aspire', 'mobilize', 'participation', 'specific',
       'participatory', 'illusion', 'dweller', 'imply', 'effectively', 'show sympathy for…', 'recommendation',
       'impersonal', 'assault', 'superstition', 'comply', 'consequence', 'formulation', 'doubt', 'cement',
       'investment  ：', 'injection', 'pursuit', 'industrial', 'hold back', 'verbal', 'infirm', 'mass', 'philosophy',
       'influence', 'curiosity', 'democratic', 'dealership', 'in doubt', 'embrace', 'reveal', 'scrupulous',
       'recognition', 'preoccupation', 'offline', 'degree', 'manufacture', 'publicly', 'universalize', 'terminate',
       'emotional', 'nevertheless', 'uneconomic', 'depict', 'mystery', 'implement', 'investor', 'adoptive', 'oblige',
       'underlying', 'council', 'genealogist', 'stock price', 'prime', 'philosophical', 'block', 'compel',
       'infrastructure', 'comfort', 'pilgrim   prestige   index', 'implementation', 'informativeness', 'provoke',
       'final', 'combine', 'draw back', 'supplement', 'monetary', 'previously', 'chronic', 'nerve', 'bulk', 'ideology',
       'palliate', 'species', 'anthropologist', 'opponent', 'questionable', 'brain-drain', 'collaborate', 'harmonious',
       'forbid', 'disjunction', 'account', 'overlap', 'professional', 'crop', 'physics', 'integrate', 'engage in',
       'fiscal', 'substance', 'eyebrow', 'foster', 'therapist', 'robust', 'creativity', 'perform', 'withstand',
       'scatter', 'portion', 'accessible', 'diminish', 'consider... as', 'title', 'propose', 'worthy', 'exclusive',
       'technological', 'fatal', 'unconventional', 'consumerism', 'responsibility', 'informed', 'displacement',
       'compose', 'stress', 'enable', 'entertainer', 'lengthy', 'contrast', 'intelligently', 'vast', 'supervise',
       'exhibition', 'dramatically', 'denominate', 'workforce', 'boom', 'be sorrowful of', 'safeguard',
       'interprovincial', 'definitely', 'endeavor', 'slogan', 'critically', 'shrinkage', 'parliament', 'determinedly',
       'vanish', 'display', 'mundane', 'resent', 'precision', 'confront', 'orchestra', 'grow', 'by no means',
       'be affiliated/attached to', 'dominant', 'cast', 'recommend', 'acceptance', 'quit', 'criminal', 'quotation',
       'drop', 'windscreen', 'reconsider', 'present', 'predecessor', 'prevalent', 'conventional', 'meaningfully',
       'privileged', 'mastery', 'worthy of', 'magnify', 'analysis', 'clause', 'laborsaving', 'investigation', 'boost',
       'in view of', 'survival', 'remain', 'procession', 'rush', 'secure', 'regime', 'sort', 'engineering',
       'self-contented', 'isolate', 'infuriating', 'challenge', 'deflation', 'government-funded', 'economics', 'ideal',
       'host', 'comfortable', 'confuse', 'vital', 'allow', 'substitute', 'discard', 'remind sb. of …', 'strategic',
       'perplexing', 'be occupied with', 'straight', 'peculiar', 'teller', 'objectiveness', 'exaggerated', 'Bible',
       'offspring', 'deem', 'purchase', 'diligent', 'inherit', 'evaluate', 'comparison', 'column', 'break even', 'odds',
       'publication', 'sophisticated', 'derive', 'probable', 'calorie', 'infer', 'explosion', 'leadership', 'restrict',
       'consent', 'moan', 'give rise to', 'object to sth./doing sth.', 'radiate', 'income', 'a fraction of', 'bang',
       'windfall', 'tissue', 'upsetting', 'consumer', 'rent', 'massive', 'commission', 'realistic', 'protein',
       'meanwhile', 'strength', 'solution', 'distort', 'more or less', 'practical experience', 'restriction', 'abreast',
       'be doomed to = be bound to = be destined to', 'hug', 'contribution', 'novelty', 'take into account', 'casually',
       'le', 'management', 'activate', 'depression', 'contributing', 'kit', 'in conclusion', 'abound', 'excess',
       'introduce', 'detect', 'assort', 'employment', 'expose to', 'routinely', 'at length', 'infant  5~7',
       'tide   via prep.  adolescent', ' [pl', 'gene', 'inflationary', 'observation', 'excellence', 'subject', 'seize',
       'gradual', 'physician', 'federation', 'unfavorable', 'bury one’s hein the sand', 'hostility', 'enthusiastic',
       'advisable', 'influential', 'fossil', 'discern', 'consumption', 'harm', 'exceedingly', 'licence', 'vulnerable',
       'break into', 'hustle', 'inappropriate', 'leniency', 'ornament', 'affiliate', 'credential', 'unemployment',
       'submission[', 'object', 'alter', 'essay', 'sensible', 'reside', 'blunt', 'contribute to', 'announcement',
       'alien', 'deserve sth.', 'feedback', 'stabilize', 'mild', 'approximate', 'engage with', 'frequent',
       'fundamental', 'bound', 'hostile', 'adaptiveness', 'proof', 'downshift', 'be critical of', 'surgeon', 'humanity',
       'client', 'concerned', 'occur', 'semiconductor', 'bury', 'party', 'enthusiastically', 'fragmented',
       'workstation', 'abundant', 'intrude', 'mission', 'transformation', 'be committed to', 'suffer', 'typically',
       'procedure', 'appalling', 'combat', 'ample', 'professionalism', 'nonfundamentalist', 'resistant', 'merchandise',
       'quest', 'cloak', 'outlet', 'perplexed', 'interpersonal', 'labor', 'dream', 'commend', 'clue', 'materialistic',
       'anatomy', 'eventually', 'be conscious of', 'inject', 'describe', 'disintegrate', 'conference', 'mean', 'cost',
       'circulation', 'adequate', 'productivity', 'intellectual', 'be aware of', 'hurt', 'preserve', 'cease',
       'preconception', 'exhibit', 'intensive', 'company', 'effortless', 'rut', 'dense', 'mold sb/sth.into sb/sth.',
       'famine', 'obtain', 'win', 'involve', 'label', 'university', 'census', 'undoubtedly', 'in contact with',
       'at odds with', 'prejudice', 'respected', 'fault', 'prospect', 'on the decline', 'description', 'stressed-out',
       'restoration', 'unaffordable', 'muscle', 'halo', 'outweigh', 'exert', 'oriented', 'acceptable', 'improve',
       'replacement', 'bait', 'manipulate', 'revenue', 'comprehension', ' 10', 'excel', 'complicated',
       'be correlated with', 'typical', 'compelling', 'recruit', 'let', 'account for', 'performer', 'abide',
       'extension', 'employ', 'maintain', 'psychological', 'unveil', 'favor', 'hence', 'plight', 'advocate',
       'distribution channel', 'instrumentalist', 'handle', 'frightening', 'interpret', 'claw', 'be bound up with',
       'pipeline in the pipeline', 'in earnest', 'wind', 'intense', 'posterity', 'universe', 'nonverbal', 'analogous',
       'preference', 'digestive', 'reflect on', 'instantaneously', 'live off', 'allowance', 'alphabet']


